// lib/ai/groqBudget.ts
//
// Shared daily cap on Groq API calls for the whole deployment (all users share
// one GROQ_API_KEY / org quota). Per-IP limits in rateLimit.ts do not protect this.

import { edgeKvExpire, edgeKvGet, edgeKvIncr } from '@/lib/kv/edgeRead';

const KEY_PREFIX = 'ai-thesis:groq-budget:';
const WINDOW_SECONDS = 24 * 60 * 60;
/** Conservative default for Groq free tier (~1k RPD, ~200k TPD, heavy prompts). */
const DEFAULT_DAILY_GROQ_CALLS = 50;

const localBuckets = new Map<string, { count: number; resetAt: number }>();

export function getGroqDailyBudgetLimit(): number {
  const raw = process.env.AI_THESIS_DAILY_GROQ_BUDGET?.trim();
  if (!raw) return DEFAULT_DAILY_GROQ_CALLS;
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isFinite(parsed) || parsed < 1) return DEFAULT_DAILY_GROQ_CALLS;
  return parsed;
}

function budgetDayKey(now = new Date()): string {
  const day = now.toISOString().slice(0, 10);
  return `${KEY_PREFIX}${day}`;
}

export type GroqBudgetResult =
  | { allowed: true; remaining: number; limit: number }
  | { allowed: false; retryAfterSec: number; limit: number };

function checkLocalGroqBudget(limit: number): GroqBudgetResult {
  const key = budgetDayKey();
  const now = Date.now();
  const bucket = localBuckets.get(key);
  if (!bucket || now >= bucket.resetAt) {
    localBuckets.set(key, { count: 0, resetAt: now + WINDOW_SECONDS * 1000 });
    return { allowed: true, remaining: limit, limit };
  }
  if (bucket.count >= limit) {
    return {
      allowed: false,
      retryAfterSec: Math.max(1, Math.ceil((bucket.resetAt - now) / 1000)),
      limit,
    };
  }
  return { allowed: true, remaining: Math.max(0, limit - bucket.count), limit };
}

function recordLocalGroqCall(): void {
  const key = budgetDayKey();
  const now = Date.now();
  const bucket = localBuckets.get(key);
  if (!bucket || now >= bucket.resetAt) {
    localBuckets.set(key, { count: 1, resetAt: now + WINDOW_SECONDS * 1000 });
    return;
  }
  bucket.count += 1;
}

/** Check whether another Groq API call is allowed today (UTC day, rolling 24h TTL in KV). */
export async function checkGroqDailyBudget(): Promise<GroqBudgetResult> {
  const limit = getGroqDailyBudgetLimit();
  const key = budgetDayKey();
  const raw = await edgeKvGet(key);
  const used = raw ? Number.parseInt(raw, 10) || 0 : 0;

  if (raw == null) {
    const local = checkLocalGroqBudget(limit);
    if (!local.allowed) return local;
    return { allowed: true, remaining: limit, limit };
  }

  if (used >= limit) {
    return { allowed: false, retryAfterSec: secondsUntilUtcMidnight(), limit };
  }
  return { allowed: true, remaining: Math.max(0, limit - used), limit };
}

/** Record one Groq API call against the shared daily budget. */
export async function recordGroqApiCall(): Promise<void> {
  const key = budgetDayKey();
  const count = await edgeKvIncr(key);
  if (count == null) {
    recordLocalGroqCall();
    return;
  }
  if (count === 1) {
    await edgeKvExpire(key, WINDOW_SECONDS);
  }
}

function secondsUntilUtcMidnight(now = new Date()): number {
  const midnight = new Date(now);
  midnight.setUTCHours(24, 0, 0, 0);
  return Math.max(60, Math.ceil((midnight.getTime() - now.getTime()) / 1000));
}

export function formatGroqBudgetError(retryAfterSec: number, limit: number): string {
  const hours = Math.ceil(retryAfterSec / 3600);
  if (hours <= 1) {
    return `Shared AI thesis capacity for today is used (${limit} Groq calls). Try again in about an hour, or load a ticker another member already generated today.`;
  }
  return `Shared AI thesis capacity for today is used (${limit} Groq calls). Resets at UTC midnight — or try a ticker already generated by someone in your group today.`;
}
